site_name: Imputation-Bot 1.0.0
theme: readthedocs

nav:
- Installation: index.md
- Configure Instances: instances.md
- Getting Started: getting-started.md
- Submit Jobs: submit-jobs.md
- List Jobs: list-jobs.md
- Download Results: download-results.md
- Manage Projects: projects.md
- Reference Panels: reference-panels.md
- Public Instances: public-instances.md
- API Reference: api-reference.md
- FAQ: faq.md
- Contact: contact.md

repo_name: lukfor/imputationbot
repo_url: https://github.com/lukfor/imputationbot
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt
      link: https://github.com/lukfor/imputationbot

markdown_extensions:
    - toc:
        permalink:
    - admonition:
